name: Auto-Merge PR for .txt Files in cdn Folder

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so that we can do proper diffs

      - name: Fetch main branch
        run: |
          git fetch origin main  # Ensure the main branch is available

      - name: Verify PR contents
        run: |
          # Get the list of files changed in the pull request
          FILES_CHANGED=$(git diff --name-only origin/main...HEAD)
          echo "Files changed: $FILES_CHANGED"

          # Check if any .txt files in the cdn/ folder were modified
          echo "$FILES_CHANGED" | grep -q "^cdn/.*\.txt$" || exit 1

      - name: Auto-merge the PR
        if: success()
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
            -d '{"merge_method":"squash"}'
