name: Automerge PRs
on:
  pull_request:
    branches:
      - main
    paths:
      - 'cdn/**/*.txt'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch main branch
        run: git fetch origin main:main
      - name: Check changed files
        run: |
          PR_SHA=$(jq -r '.pull_request.head.sha' < "$GITHUB_EVENT_PATH")
          FILES_CHANGED=$(git diff --name-only main..$PR_SHA)
          echo "Files changed: $FILES_CHANGED"
          echo "$FILES_CHANGED" | grep -q "^cdn/.*\.txt$" || exit 1
      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Automatically merged PR"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
