name: Automerge New CDN Files
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for new files
        id: check_files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            new_cdn_txt:
              - added: 'cdn/**/*.txt'

      - name: Automerge PR
        if: steps.check_files.outputs.new_cdn_txt == 'true'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Automatically merged PR adding new .txt files to cdn"
