name: Auto-Accept PR with .txt Files

on:
  pull_request:
    paths:
      - 'cdn/*.txt'

jobs:
  auto_accept_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches and commit history

      - name: Fetch main branch
        run: |
          git fetch origin main  # Ensure 'main' branch is fetched

      - name: Get changed files
        run: |
          # Compare the PR branch with the main branch
          FILES_CHANGED=$(git diff --name-only origin/main..HEAD)
          echo "Changed files: $FILES_CHANGED"
          # Check if any .txt files are present in the changed files
          if echo "$FILES_CHANGED" | grep -qE '\.txt$'; then
            echo "TXT files found."
          else
            echo "No TXT files found."
            exit 1
          fi

      - name: Auto-merge PR
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use your custom GH token
        run: |
          echo "Automatically merging PR"
          gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }} --auth $GH_TOKEN
