name: Auto-Accept PR with .txt Files

on:
  pull_request:
    paths:
      - 'cdn/*.txt'

jobs:
  auto_accept_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches and commit history

      - name: Get changed files
        run: |
          # Ensure we're on the PR branch
          git fetch origin main
          git diff --name-only origin/main...${{ github.event.pull_request.head.sha }} > files_changed.txt
          cat files_changed.txt
          
          # Check for .txt files
          if grep -qE '\.txt$' files_changed.txt; then
            echo "TXT files found."
          else
            echo "No TXT files found."
            exit 1
          fi

      - name: Auto-merge PR
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use your custom GH token
        run: |
          echo "Automatically merging PR"
          gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }} --auth $GH_TOKEN
