name: Automerge PRs

on:
  pull_request:
    paths:
      - 'cdn/**/*.txt'

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          git fetch origin main
          FILES_CHANGED=$(git diff --name-only origin/main...HEAD)
          echo "Changed files: $FILES_CHANGED"
          if echo "$FILES_CHANGED" | grep -qvE '^cdn/.*\.txt$'; then
            echo "Non .txt files or files outside /cdn directory detected."
            exit 1
          fi

      - name: Automerge PR
        uses: reitermarkus/automerge@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
