name: Automerge PRs

on:
  pull_request:
    paths:
      - 'cdn/**/*.txt'

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.additions > 0 && github.event.pull_request.changed_files == github.event.pull_request.additions
    steps:
      - name: Automerge PR
        uses: reitermarkus/automerge@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
