name: Auto-Merge PR for .txt Files in cdn Folder

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify PR contents
        run: |
          FILES_CHANGED=$(jq -r '.pull_request.head.sha' < "$GITHUB_EVENT_PATH" | xargs -I {} git diff --name-only origin/main..{})
          echo "Files changed: $FILES_CHANGED"
          echo "$FILES_CHANGED" | grep -q "^cdn/.*\.txt$" || exit 1

      - name: Auto-merge the PR
        if: success()
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
            -d '{"merge_method":"squash"}'
